### ISSUE TITLE
Kickback sponsor image is a broken link

### ISSUE THREAD

**Issue by NevilleS** [EmpireJS/2016.empirejs.org#16]
Just thought you'd want to know! Probably just needs a production-kick-in-the-pants:
![image](https://cloud.githubusercontent.com/assets/1834295/15483923/5c973640-2105-11e6-9bc7-a1cc8432cb19.png)

**Comment by indexzero** [comment]
Pants officially kicked. Thanks for reporting the issue!

**Comment by NevilleS** [comment]
No problem!
